[graph]
targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
]

[advisories]
version = 2
yanked = "deny"
ignore = [
    # this is a timing attack against using the rsa crate for encryption, but
    # we only use rsa decryption here
    "RUSTSEC-2023-0071",
    # this is only a warning about being unmaintained, the only known
    # undefined behavior is in a function we don't use
    "RUSTSEC-2025-0069",
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
deny = [
    { name = "openssl-sys" },
]
skip = [
    # https://github.com/darfink/region-rs/pull/25
    { name = "bitflags", version = "1.3.2" },
    { name = "bitflags", version = "2.4.1" },
    # ssh-agent-lib is holding this back
    { name = "thiserror", version = "1.0.69" },
    { name = "thiserror", version = "2.0.17" },
    { name = "thiserror-impl", version = "1.0.69" },
    { name = "thiserror-impl", version = "2.0.17" },
    # until the rand 0.8 -> 0.9 transition finished making its way through
    # the crate ecosystem
    { name = "rand", version = "0.8.5" },
    { name = "rand", version = "0.9.2" },
    { name = "rand_core", version = "0.6.4" },
    { name = "rand_core", version = "0.9.3" },
    { name = "rand_chacha", version = "0.3.1" },
    { name = "rand_chacha", version = "0.9.0" },
    { name = "getrandom", version = "0.2.16" },
    { name = "getrandom", version = "0.3.4" },
]

[licenses]
version = 2
allow = [
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Apache-2.0",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
    "Zlib",
]
exceptions = [
    { name = "ring", allow = ["OpenSSL", "MIT", "ISC"] }
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 }
]
